import "./globals.css";
import { crimsontext, oxygen } from "./fonts/font";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Digital Prescription System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimsontext} ${oxygen}`}
      >
        {children}
      </body>
    </html>
  );
}
